### ISSUE TITLE
Session data handling

### ISSUE THREAD

**Issue by ChicagoDave** [thiloplanz/glulx-typescript#24] opened 2016-05-15 14:37 UTC
So this is the hack that I think makes the EngineWrapper more useful and deprecates the need for that "look" command or even needing the undo code at all. In the "deliverOutput" method of Engine.ts, we should call the "saveToQuetzal" routine and store the sessionData in a public property of the Engine.

          public sessionData: FyreVM.Quetzal;
      	  private deliverOutput(){
		 if (this.outputReady){
		 	let pack = this.outputBuffer.flush();
                        this.saveToQuetzal(???,???);
		 	this.outputReady(pack);
		 }
	  }

We should still support standard save and undo, but the FyreVMWeb.Manager class would ignore those completely and use the offered sessionData property to manage all turn data. I did this at one point when I was creating a client/service version of FyreVM called Zifmia. I was still doing that extra "look" thing which you've adopted though and we really need to get rid of that. There's no need. We have the ability to create the quetzal stream within the engine at any given time. Why not just do it after every turn has completed?

I plan to add an extension class called FyreVMWeb.SessionManager that will combine the channel data, the sessionData, and the associated command all in a package and then store every turn like that. So the UI will just determine which turn the player wants, reload that data, and display the previous results. At that point we don't even need to re-execute anything in the VM. All historical turns are complete and known. Now, if the user types a new command at an historical point, I might want to implement a branching mechanism, but that's probably a different extension class FyreVMWeb.BranchingSessionManager.

So I plan to implement two session related classes:

FyreVMWeb.StandardSessionManager - This will do everything the player expects for save, undo, restore. They won't even know there's a different implementation underneath the covers. In the case of going back n turns, I would just truncate the "future" turn data and extend the storage from the newly executed turn.

FyreVMWeb.BranchingSessionManager - This will branch storage if the user goes back and enters a new command. I'll actually check all branches from a point and see if that command is in a branch. If not, we create a new branch of session data. I've done this in Zifmia, so it's a known solution.

The key is to have the engine produce the Quetzal data every turn. Not leave this to the EngineWrapper and that extra "look" command.

**Comment by thiloplanz** [comment] 2016-05-16 01:00
Closing as duplicate of #16

**Closed by thiloplanz** 2016-05-16 01:00 UTC
